### ISSUE TITLE
chown: /storage: Permission denied

### ISSUE THREAD

**Issue by ep5000** [Ezka77/xen-orchestra-ce#13]
I get the following output when running docker-compose up:

XO_redis     | find: .: Permission denied
XO_redis     | chown: .: Permission denied
XO_server    | chown: /storage: Permission denied
XO_redis exited with code 1
XO_redis     | find: .: Permission denied
XO_redis     | chown: .: Permission denied
XO_redis     | find: .: Permission denied
XO_redis     | chown: .: Permission denied
XO_redis     | find: .: Permission denied
XO_redis     | chown: .: Permission denied
XO_server exited with code 1

Both XO_redis and XO_server appear to restart continually forever.

**Comment by Ezka77** [comment]
This should help, follow the steps from this previous issue:
https://github.com/Ezka77/xen-orchestra-ce/issues/9#issuecomment-397909625
