### ISSUE TITLE
Time out of sync with host

### ISSUE THREAD

**Issue by jmccoy555** [Ezka77/xen-orchestra-ce#16]
Hi, 

Firstly thanks for this image.

However, XO flags an error about the time not being in sync with the host, I'm in the UK.

Running date on the host give the correct time and timezone - BST, running date on the XO docker does not, it returns UTC which is an hour behind at the moment. 

I have tried the usual tricks to get the timezone passed through, but no luck.

Any ideas please? 

Cheers.

**Comment by christianuhlmann** [comment]
add enviroment variable

TZ=Europe/Berlin (for Germany)

in compose file its look like:

>         environment:
>             - TZ=Europe/Berlin

hope that helps
