### ISSUE TITLE
Backup-NG uses a lot of memory

### ISSUE THREAD

**Issue by aramirez-capacity** [Ezka77/xen-orchestra-ce#17]
I initially reported this issue upstream, to the XO team, but after some testing we determined the fault was here. Original issue is here: https://github.com/vatesfr/xen-orchestra/issues/4612
I'm taking a look at the Dockerfile, as suggested the last comment in the linked thread, but I'm not familiar with the tools used here (alpine, node, etc). Could you take a look too, please?

**Comment by aramirez-capacity** [comment]
Hi. Any news on this?

**Comment by Ezka77** [comment]
Hi, as I'm not using CIFS it's gonna be quite hard to me to debug. But I'll have a look asap, maybe it's an issue with the CIFS-utils on Alpine Linux.

**Comment by Ezka77** [comment]
I've added the CIFS tools in the docker image BUT I think it's a bug in the command tool itself ; so until it's fix (if it is fiexed one day) may I advise to try another docker ? or the official appliance obviously.

Have a look to https://github.com/ronivay/xen-orchestra-docker image it uses CentOS as base may be there is no issue with this version.

I close this issue as I can't do much about it, if you end up with a good solution feel free to comment here.

**Comment by aramirez-capacity** [comment]
Hi,
thanks for your help.
I ended up using this other image: brijohn/xen-orchestra
I think that one's working, but I have some other issues and cant test properly. :-P

**Comment by Ezka77** [comment]
If you have time you can build this container with alpine 3.6 OR 3.11 - the version with the memory leak you use run on alpine 3.8 - maybe previous or next version will work.

Clone this repo, switch to **build** branch: `git checkout build`

To change the alpine version of the running container use this [line in the Dockerfile](https://github.com/Ezka77/xen-orchestra-ce/blob/02c9e06311c1c950643bb2d45d16c49e8ca9c2fd/alpine/Dockerfile#L48) and replace `3.8` by `3.6` or `3.11`.

Type `make build` in `alpine/` directory and it will build the image locally. When done run the docker-compose as usual IF IT START do your test.

It should start with 3.6 version as Node is build with this one but I'm not sure about the 3.11.

If it seems a bit too complex for you, I can build an "experimental" image version for your tests, let me know ;)

**Comment by Ezka77** [comment]
I've build an image for testing purpose running on alpine 3.11:
Edit your docker-compose or whatever to use this image: `ezka77/xen-orchestra-ce:experimental`

Have a test on your CIFS backups and let me know if it work ;)

**Comment by aramirez-capacity** [comment]
I just run a test and it seems to work fine: the backup was successful and there was no leak. Thanks!

**Comment by Ezka77** [comment]
humm well I think I've already bumped the running image to 3.8 for a missing pkg/bug/issue I've found, I'll bump the latest to 3.11 asap.
