### ISSUE TITLE
Extra Plugins

### ISSUE THREAD

**Issue by tuzzmaniandevil** [Ezka77/xen-orchestra-ce#23]
XOA have added some new plugins:
- netdata
- sdn-controller
- telemetry
- web-hooks

Would it be possible to add it to this build, please?

**Comment by Ezka77** [comment]
Hi,
netdata and telemetry seem to not being part of xen-orchestra git repos (in master branch) ; I can find references in js code but not as plugins. If they are external plugin add a link or a way to add them here I'll see if I can add them.

I'll add web-hooks and sdn-controller asap.
