### ISSUE TITLE
Logs become unavailable after upgrading from 5.49 to 5.54

### ISSUE THREAD

**Issue by clausreinprecht** [Ezka77/xen-orchestra-ce#24]
aftere upgrading from 5.49 (before latest) to the lastests container version the logs listing (in backup-ng and settings/logs) is running endlessly without any outcome... so there is no backup job result or status of the job indicated (cant be seen).

**Comment by CAPS3** [comment]
Can confirm I'm also experiencing this issue. 
Updated container & container host VM, as well as ensuring xcp-ng hypervisor host was patched up-to-date and rebooted. I've attached the browser console error that I receive (regardless of whether I use hostname (pi.hole) or ip address...)

![temp2](https://user-images.githubusercontent.com/43501711/71545301-a884ad00-29dd-11ea-9fc5-000ce65a8d63.jpg)

**Comment by Ezka77** [comment]
Hi,

I've push a new latest, can you give it a try ? I think it comes that in the latest xo version the configuration file change and using the old one can result to a broken install.

**Comment by CAPS3** [comment]
I've ran the following: 

> docker-compose down
> docker-compose pull
> docker-compose up -d

and logs are now appearing normally as expected.

Thankyou so much for your help!
