### ISSUE TITLE
plugin.load failed error 

### ISSUE THREAD

**Issue by hkjang** [Ezka77/xen-orchestra-ce#27]
Hello~ thank you for your project first. 

When i add transport-email plug-in on XOA, it is occured error msg. (plugin not configured)

plugin.load
{
  id : transport-email
}
{  
  code : 10,
  data : {}   ,
  message : plugin not configured ,
  name : XoError ,
  stack : XoError: Plugin not configured ,
}

Do you have any idea to fix this error?

**Comment by Ezka77** [comment]
Do you configure it before enabling it ?

I think the UI is a bit awkward in the plugin tab. If you press the "grey-to-green swipe box" on the left before pressing the "blue plus sign button" on the right and do/check the configuration it end with an error about configuration.

NB: I mean obviously if your plugin is configured using the "blue plus sign button" is not required, but without a proper configuration you have to do that BEFORE using the "swipe button". Not sure if I'm clear here lol

**Comment by hkjang** [comment]
oh~ i got it. thank you. It is a little bit strange UX and poor alert message but it's cool~ thanks !
