### ISSUE TITLE
sdn-controller doesn't create certs

### ISSUE THREAD

**Issue by jmccoy555** [Ezka77/xen-orchestra-ce#28]
I've tried to enable the sdn plugin, but it just hangs forever.

The sdn-controller folder is created in the docker volume, but that's it. 

Does this work for anyone, or is it maybe missing some dependencies? 

Not sure if this helps https://xcp-ng.org/forum/topic/1731/sdn-certs-module

**Comment by Ezka77** [comment]
I think the plugin cannot create the certs as this docker doesn't have openssl tool or so.
Let me see if I can find the requirements, may be I can generate the certs in the build container and import them in the running one.

**Comment by jmccoy555** [comment]
Hi, great. From that thread it sounds like it might be node-openssl-cert????

**Comment by Ezka77** [comment]
From JS code it uses a node modules yes, but in the backend it uses openssl tool from system, so
I've picked the simple solution: add openssl into the running container, this way the plugin can build his own certificate with the rights parameters.

I've started a build it should be available soon on docker hub.

**Comment by Ezka77** [comment]
Give a try to the latest tag and let me know if there is still an issue with this plug-in.

**Comment by jmccoy555** [comment]
Looks like that's done the trick, the plugin now enables. 

Thanks
