### ISSUE TITLE
Why use `<< *logging` instead of `: *logging`?

### ISSUE THREAD

**Issue by retnikt** [Ezka77/xen-orchestra-ce#29]
Random question, but in `docker-compose.yml`, you use
```yaml
logging:
    <<: *logging
```
when
```yaml
logging: *logging
```
could be used instead for the same outcome, which is simpler (IMO) to understand. Is there any reason for this?

**Comment by Ezka77** [comment]
Yep same outcome, it is a YAML Merge type, it allows to add specific redis logging configuration below but, as here, there isn't any configuration you can use YAML Anchors.

Anyway YAML Anchors or Merge, this file is a template, I think the Merge gives you the flexibility to customize this part easily and I've keep it from an old configuration. At least I should rename this reference which is more confusing than using `<<:` or not ;-)

**Comment by retnikt** [comment]
Ah, I see. TIL
