### ISSUE TITLE
thoughts on https?

### ISSUE THREAD

**Issue by marklester** [Ezka77/xen-orchestra-ce#33]
I am curious if you thought to make this image use https?

**Comment by Ezka77** [comment]
Hi,

Well, you're free to proxy this docker with any nginx/apache/httpd docker of your choice, using your certificates and configured for your network. I think it's the simpler way to go here. The docker infrastructure is simple enough to allow you to make a virtual network and there is plenty of well prepared, easy to configure, and easy to run docker images of http proxy software. 

And from the docker-compose provided here I guess it will took about a minute or so to run this container behind a proxy like the [jwilder/nginx](https://hub.docker.com/r/jwilder/nginx-proxy) ; it may require your own xoa configuration file too, but quite easy to mount your file over the one in this image. But may be it doesn't suit your needs.

Feel free to make a patch request or give more details about the configuration that you think of, I'm always happy to discuss around new ideas or functionalities requests.

**Comment by marklester** [comment]
ok thanks!
