### ISSUE TITLE
Parameter to set node memory?

### ISSUE THREAD

**Issue by sampleford** [Ezka77/xen-orchestra-ce#37]
Title says it all - I wonder if it would be possible to have a config var that would change the call of `./bin/xo-server` to `./bin/node --max-old-space-size=$NODE-MEMORY ./bin/xo-server` to cater for scenarios (particularly backups) that need more memory.

Great image and really appreciate your efforts :)

**Comment by Ezka77** [comment]
Hi,

Did you try to set an env vars like: `NODE_OPTIONS='--max_old_space_size=2048'` ?
You can use the `docker-compose.yml` and add this var in the `environment:` section of the xen-orchestra service.

**Comment by sampleford** [comment]
Ahh, that’s superb; hadn’t thought about using the environmental var pass through. Thanks!
