### ISSUE TITLE
[redis] Error: TCP listening socket

### ISSUE THREAD

**Issue by rafaelmr2** [Ezka77/xen-orchestra-ce#38]
I was having this error on my Manjaro with redis:

```
Could not create server TCP listening socket ::*:6379: unable to bind socket, errno: 97
```

I substitute "command" with:
```
command: ["redis-server", "--bind", "redis", "--port", "6379"]
```

An it's works.

**Comment by Ezka77** [comment]
Hi Rafaelmr2,

That's a weird error as the default docker-compose file use the command line provided by the redis docker documentation. Can you try to run something like:
`docker run --name some-redis -d redis`

and if it works:
`docker run --name some-redis -d redis redis-server --appendonly yes`

Maybe an issue with the protected-mode of redis ? I think from the docker we use it is set to off but it may have changed. If the command above gives you the same error, you can try:
`docker run --name some-redis -d redis redis-server --appendonly yes --protected-mode off`
The bind option you give seems to force redis to listen on the local "machine" (the container here) and default redis configuration only binds to localhost for local services unless the protected-mode is off ... or a password is set, which should be done by our configuration but ...
 
Or may be there is already a Redis on your system ? but it should not interfere with the one in the docker as each one are on a separated network and the one for XOA is not public to the host machine.

Anyway, you find a suitable configuration for your system ! Thanks for sharing the issue and your solution ;-) if this issue become recurring I'll give a more thorough look into it.
