### ISSUE TITLE
How do I connect to existing redis server?

### ISSUE THREAD

**Issue by GiganteX** [Ezka77/xen-orchestra-ce#40]
Hi. 
I don't use docker-compose, I just add the service to my swarm (docker service create...). 
And I have an existing redis server. How can I tell XO to use my redis server?

**Comment by GiganteX** [comment]
Never mind, I figured it out. Seems I just had to make sure the redis instance was in the same network and named "redis"!

**Comment by Ezka77** [comment]
👍 

Here the line that XOA use to connect to a redis: https://github.com/Ezka77/xen-orchestra-ce/blob/6208f1444547fde25ea72c5252431f639b173768/alpine/remco/templates/config.toml#L129

The simplest way to use an external redis is what you do 👍  ; it could be a bit more trickier to configure port and base number.
