### ISSUE TITLE
 New Backup setup failures 

### ISSUE THREAD

**Issue by ventu** [Ezka77/xen-orchestra-ce#45]
Good morning,

running Xcp-ng 8.2 with Docker XOA setup. I'm attempting to push Backups to SMB share on a Seagate Personal NAS for about 3 months but encountering errors:

`        Duration: an hour
        Error: STATUS_FILE_CLOSED (0xC0000128) : An I/O request other than close and several other special case operations was attempted using a file object that had already been closed.
    Start: Jun 3, 2021, 12:00:18 AM
    End: Jun 3, 2021, 1:24:40 AM
    Duration: an hour
    Error: STATUS_FILE_CLOSED (0xC0000128) : An I/O request other than close and several other special case operations was attempted using a file object that had already been closed.

Start: Jun 3, 2021, 12:00:07 AM
End: Jun 3, 2021, 1:24:41 AM
Duration: an hour
Error: all targets have failed, step: writer.transfer()
Type: full`

It sees the Share correctly, it tests fine but after the full hour of backups I get this.

**Comment by Ezka77** [comment]
Hi,
as I'm not using SMB I'll might struggle to help you but we can try:
 - are you running the container with `privileged: true` in docker/compose configuration ? it might help to solve some r/w permission or get  some new errors.
- does this push on SMB worked before ? or it never did.

**Comment by ventu** [comment]
You are a life saver and stopped me from messing with a Raspberry Pi/NFS setup for a temp solution till the real gear gets here. It works after removing the # by `privileges: true`. I can backup and restore all day long. Thank you!
