### ISSUE TITLE
All "Stats" tabs showing errors

### ISSUE THREAD

**Issue by JohnyR** [Ezka77/xen-orchestra-ce#46]
The Stats tabs in all areas (VMs, Disks, Host, etc.) are showing "No stats.". Checking the logs, it seems to be throwing an internal error.

Here's a snippet of the error:

`vm.stats
{
  "id": "9f55ab32-46b5-06aa-50d5-8fddfaf6fbbf",
  "granularity": "seconds"
}
{
  "code": "INTERNAL_ERROR",
  "params": [
    "(Failure
  \"Expected string, got '{uuid:S(c3708d5e-e0f2-428c-91c4-2279c227d7f4);name_label:S(x);name_description:S(x XenServer);memory_overhead:I(1027997696);allowed_operations:...'\")"
  ],
  "call": {
    "method": "host.get_record",
    "params": [
      {
        "uuid": "c3708d5e-e0f2-428c-91c4-2279c227d7f4",
        "name_label": "x",
        "name_description": "x XenServer",
        "memory_overhead": 1027997696,
        "allowed_operations": [
          "vm_migrate",
          "provision",
          "vm_resume",
          "evacuate",
          "vm_start"
        ],
        "current_operations": {},
        "API_version_major": 2,
        "API_version_minor": 14,
        "API_version_vendor": "XenSource",
        "API_version_vendor_implementation": {},
        "enabled": true,
        "software_version": {
          "product_version": "8.1.0",
          "product_version_text": "8.1",
          "product_version_text_short": "8.1",
          "platform_name": "XCP",
          "platform_version": "3.1.0",
          "product_brand": "XCP-ng",
          "build_number": "release/quebec/master/17",
          "hostname": "localhost",
          "date": "2020-03-30",
          "dbv": "0.0.1",
          "xapi": "1.20",
          "xen": "4.13.0-8.3.xcpng8.1",
          "linux": "4.19.0+1",
          "xencenter_min": "2.14",
          "xencenter_max": "2.14",
          "network_backend": "openvswitch",
          "db_schema": "5.504"
        },
        "other_config": {
          "agent_start_time": "1628621379.",
          "boot_time": "1628621206.",
          "rpm_patch_installation_time": "1576008140.651",
          "iscsi_iqn": "iqn.2017-03.com.example:f64f8112",
          "perfmon": "<config><variable><name value=\"cpu_usage\" /><alarm_trigger_level value=\"0.5\" /><alarm_trigger_period value=\"60\" /><alarm_auto_inhibit_period value=\"3600\" /></variable></config>"
        },
        "capabilities": [
          "xen-3.0-x86_64",
          "xen-3.0-x86_32p",
          "hvm-3.0-x86_32",
          "hvm-3.0-x86_32p",
          "hvm-3.0-x86_64",
          ""
        ],
        "cpu_configuration": {},
        "sched_policy": "credit",
        "supported_bootloaders": [
          "pygrub",
          "eliloader"
        ],
        "resident_VMs": [
          "OpaqueRef:1171ebab-8264-4388-bb54-e5617e3c29c7",
          "OpaqueRef:aaed3665-58c8-46a6-a640-1360f2be3118",
          "OpaqueRef:7eb917a6-51df-4003-adb5-8dd94353e47a",
          "OpaqueRef:fedaf846-9528-9770-a157-5435acd125b4",
          "OpaqueRef:32695424-919e-0ba8-ab20-30bcebdec8be",
          "OpaqueRef:e674d66f-fb37-7cc2-a579-b2de94c9520c",
          "OpaqueRef:6d49dd1a-f5e9-8666-b9ff-e6b2439d756e",
          "OpaqueRef:e4ddd2a4-6e6e-6dd1-d09d-2f14fb7c5d6b",
          "OpaqueRef:15a9de06-2f26-4c5b-b1e2-7060e05537e2",
          "OpaqueRef:8386657b-c543-5f29-8a27-c92a6e2d4949",
          "OpaqueRef:392a81e7-be05-414a-8587-207ef210b7d4",
          "OpaqueRef:5a475ece-5938-4f1f-b07e-8ade99234072",
          "OpaqueRef:64fcb320-2aa6-4f5e-89e4-9ca17c3a8423",
          "OpaqueRef:3cbcb0d6-f342-50a8-7971-4f2aa1d0a13b",
          "OpaqueRef:5219881b-8746-d996-df96-4a8d12c45d96",
          "OpaqueRef:3e642c12-12cb-dfc1-0afb-0cbed73c101b"
        ],
        "logging": {},
        "PIFs": [
          "OpaqueRef:fd67add1-fd85-e7b5-6ea2-af4c0943be46",
          "OpaqueRef:e04c476c-424f-bbbc-5b8c-a66acfa55605",
          "OpaqueRef:c0ec2c66-6515-17b4-89d1-56625308ee26",
          "OpaqueRef:58b9b935-bd15-0882-6786-c5290dc7f12e"
        ],
        "suspend_image_sr": "OpaqueRef:32447ec3-4188-a143-119a-d0ef06b35f85",
        "crash_dump_sr": "OpaqueRef:32447ec3-4188-a143-119a-d0ef06b35f85",
        "crashdumps": [],
        "patches": [],
        "updates": [],
        "PBDs": [
          "OpaqueRef:19910c5f-6876-4423-9120-f0f375fceb49",
          "OpaqueRef:f54564f7-c887-0ebb-a161-444c40198928",
          "OpaqueRef:d8d594d1-f7f0-49d3-a747-0aeda681a9b6",
          "OpaqueRef:9b39afb2-6207-ace7-f9dd-79366bca729b",
          "OpaqueRef:6c7c60d9-2adc-a583-f68b-28760e4b88e6",
          "OpaqueRef:623b3a8c-bc27-4ce4-f415-b8ef00cd1df4",
          "OpaqueRef:536655f3-6132-4848-a3ae-3c5e8488a004",
          "OpaqueRef:2e042743-5c76-8b21-f610-829df777e8d6"
        ],
        "host_CPUs": [
          "OpaqueRef:06b04107-da6f-49d9-8655-95a26c72ed19",
          "OpaqueRef:9adad9b9-a656-4c2b-8652-cdd20e7cca4d",
          "OpaqueRef:ff5375f7-c749-4a03-bc77-6ea1155f292f",
          "OpaqueRef:42e2e9dd-b7cf-46d2-ba13-aaefe2046565",
          "OpaqueRef:17c928dd-253b-4584-ade8-dae07f94c626",
          "OpaqueRef:7f8893ef-34e4-4f8d-8754-d87f27978229",
          "OpaqueRef:931e4ebd-b3f3-41ff-ac10-45ca0e787177",
          "OpaqueRef:f0527c7d-651b-4b56-8fb2-c4652c462abb",
          "OpaqueRef:d6d18319-1ac8-48bf-b6fb-b43ebcb7a2fd",
          "OpaqueRef:8eb45ea6-18db-46b1-beb5-085f336894f8",
          "OpaqueRef:b186eb3e-b642-4604-8892-44cccf816b3e",
          "OpaqueRef:b3989447-e34e-4396-8e04-44a3f8111265",
          "OpaqueRef:a79c2650-1c2a-4562-9b59-d336a3e15000",
          "OpaqueRef:10b84e97-0db7-4deb-bede-29a18676cadb",
          "OpaqueRef:35145435-751f-4cf5-a160-2198d95570fd",
          "OpaqueRef:bce5c04c-ed29-4d46-ada4-8f83d14d0260",
          "OpaqueRef:7134da7d-d585-4ffb-99b8-dc59137cb3b5",
          "OpaqueRef:06c477e5-35df-4341-bd7c-b5abbf90336a",
          "OpaqueRef:e62f212e-5d00-41cd-97fd-8d1216744cfa",
          "OpaqueRef:9423c616-3ec3-456e-8649-6b39284f4f6d",
          "OpaqueRef:1ccf641b-97ad-42fa-ad62-75c66deb6b56",
          "OpaqueRef:5d1464a7-d182-452a-baab-b09de7b31bea",
          "OpaqueRef:f7ec9db1-e93b-4a3d-8cde-7c9b6cae392e",
          "OpaqueRef:c8fa802f-196f-4a88-aaae-a0d9b7c2365b"
        ],
        "cpu_info": {
          "cpu_count": "24",
          "socket_count": "1",
          "vendor": "GenuineIntel",
          "speed": "2504.615",
          "modelname": "Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz",
          "family": "6",
          "model": "63",
          "stepping": "2",
          "flags": "fpu de tsc msr pae mce cx8 apic sep mca cmov pat clflush acpi mmx fxsr sse sse2 ss ht syscall nx rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid pni pclmulqdq monitor est ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm cpuid_fault intel_ppin ssbd ibrs ibpb stibp fsgsbase bmi1 avx2 bmi2 erms xsaveopt",
          "features": "7ffefbff-bfebfbff-00000021-2c100800",
          "features_pv": "1fc9cbf5-f6f83203-2991cbf5-00000023-00000001-00000329-00000000-00000000-00001000-8c000400-00000000-00000000-00000000-00000000-00000000",
          "features_hvm": "1fcbfbff-f7fa3223-2d93fbff-00000423-00000001-000007ab-00000000-00000000-00001000-9c000400-00000000-00000000-00000000-00000000-00000000",
          "features_hvm_host": "1fcbfbff-f7fa3223-2d93fbff-00000423-00000001-000007ab-00000000-00000000-00001000-9c000400-00000000-00000000-00000000-00000000-00000000",
          "features_pv_host": "1fc9cbf5-f6f83203-2991cbf5-00000023-00000001-00000329-00000000-00000000-00001000-8c000400-00000000-00000000-00000000-00000000-00000000"
        },
        "hostname": "x",
        "address": "192.168.1.5",
        "metrics": "OpaqueRef:253fc8d6-ddd0-cb0e-a396-56ac7e8a5f49",
        "license_params": {
          "restrict_vswitch_controller": "false",
          "restrict_lab": "false",
          "restrict_stage": "false",
          "restrict_storagelink": "false",
          "restrict_storagelink_site_recovery": "false",
          "restrict_web_selfservice": "false",
          "restrict_web_selfservice_manager": "false",
          "restrict_hotfix_apply": "false",
          "restrict_export_resource_data": "false",
          "restrict_read_caching": "false",
          "restrict_cifs": "false",
          "restrict_health_check": "false",
          "restrict_xcm": "false",
          "restrict_vm_memory_introspection": "false",
          "restrict_batch_hotfix_apply": "false",
          "restrict_management_on_vlan": "false",
          "restrict_ws_proxy": "false",
          "restrict_vlan": "false",
          "restrict_qos": "false",
          "restrict_pool_attached_storage": "false",
          "restrict_netapp": "false",
          "restrict_equalogic": "false",
          "restrict_pooling": "false",
          "enable_xha": "true",
          "restrict_marathon": "false",
          "restrict_email_alerting": "false",
          "restrict_historical_performance": "false",
          "restrict_wlb": "false",
          "restrict_rbac": "false",
          "restrict_dmc": "false",
          "restrict_checkpoint": "false",
          "restrict_cpu_masking": "false",
          "restrict_connection": "false",
          "platform_filter": "false",
          "regular_nag_dialog": "false",
          "restrict_vmpr": "false",
          "restrict_vmss": "false",
          "restrict_intellicache": "false",
          "restrict_gpu": "false",
          "restrict_dr": "false",
          "restrict_vif_locking": "false",
          "restrict_storage_xen_motion": "false",
          "restrict_vgpu": "false",
          "restrict_integrated_gpu_passthrough": "false",
          "restrict_vss": "false",
          "restrict_guest_agent_auto_update": "false",
          "restrict_pci_device_for_auto_update": "false",
          "restrict_xen_motion": "false",
          "restrict_guest_ip_setting": "false",
          "restrict_ad": "false",
          "restrict_ssl_legacy_switch": "false",
          "restrict_nested_virt": "false",
          "restrict_live_patching": "false",
          "restrict_set_vcpus_number_live": "false",
          "restrict_pvs_proxy": "false",
          "restrict_igmp_snooping": "false",
          "restrict_rpu": "false",
          "restrict_pool_size": "false",
          "restrict_cbt": "false",
          "restrict_usb_passthrough": "false",
          "restrict_network_sriov": "false",
          "restrict_corosync": "true",
          "restrict_zstd_export": "false"
        },
        "ha_statefiles": [],
        "ha_network_peers": [],
        "blobs": {},
        "tags": [],
        "external_auth_type": "AD",
        "external_auth_service_name": "x",
        "external_auth_configuration": {
          "domain": "x",
          "user": "x"
        },
        "edition": "xcp-ng",
        "license_server": {
          "address": "localhost",
          "port": "27000"
        },
        "bios_strings": {
          "bios-vendor": "American Megatrends Inc.",
          "bios-version": "3801",
          "system-manufacturer": "ASUS",
          "system-product-name": "All Series",
          "system-version": "System Version",
          "system-serial-number": "System Serial Number",
          "baseboard-manufacturer": "ASUSTeK COMPUTER INC.",
          "baseboard-product-name": "X99-A/USB 3.1",
          "baseboard-version": "Rev 1.xx",
          "baseboard-serial-number": "150342285800254",
          "oem-1": "Xen",
          "oem-2": "MS_VM_CERT/SHA1/bdbeb6e0a816d43fa6d3fe8aaef04c2bad9d3e3d",
          "oem-3": "Default string",
          "oem-4": "Default string",
          "oem-5": "SAMUI",
          "oem-6": "Default string",
          "hp-rombios": ""
        },
        "power_on_mode": "",
        "power_on_config": {},
        "local_cache_sr": "OpaqueRef:32447ec3-4188-a143-119a-d0ef06b35f85",
        "chipset_info": {
          "iommu": "false"
        },
        "PCIs": [
          "OpaqueRef:d4ac8b2b-e2c3-436d-b94b-6d268ccf9239",
          "OpaqueRef:a3e2dd8f-eb0a-6deb-0337-1f6dceee2f8c",
          "OpaqueRef:a1e32462-e988-1b19-de32-39ed67b1f6a5",
          "OpaqueRef:9cd3f3c6-cbd0-4a03-9bc5-a9547802f973",
          "OpaqueRef:6f238d61-cd59-4025-bf8b-e8e2c8ebfe83",
          "OpaqueRef:5f1626fa-2042-4fdb-ab4d-fd60f753bfde",
          "OpaqueRef:55eeb799-d7c1-8074-f62a-b1e6b946db16",
          "OpaqueRef:1bdc4aa3-405f-a3cf-89cf-39b31a1f3c21",
          "OpaqueRef:145e02b5-a2bf-2ee1-9d75-5089039e0179",
          "OpaqueRef:0e4b97c7-911e-4398-938b-0e75e3af1316",
          "OpaqueRef:09259b2b-c7f4-11da-bf0b-8086d756dbb4"
        ],
        "PGPUs": [
          "OpaqueRef:fcdad82c-b279-4f55-a366-38ec59a05d96"
        ],
        "PUSBs": [
          "OpaqueRef:9d0e79c3-52a3-45ed-ace4-cc843f5aa877"
        ],
        "ssl_legacy": true,
        "guest_VCPUs_params": {},
        "display": "enabled",
        "virtual_hardware_platform_versions": [
          0,
          1,
          2
        ],
        "control_domain": "OpaqueRef:3e642c12-12cb-dfc1-0afb-0cbed73c101b",
        "updates_requiring_reboot": [],
        "features": [],
        "iscsi_iqn": "iqn.2017-03.com.example:f64f8112",
        "multipathing": false,
        "uefi_certificates": ""
      }
    ]
  },
  "message": "INTERNAL_ERROR((Failure
  \"Expected string, got '{uuid:S(c3708d5e-e0f2-428c-91c4-2279c227d7f4);name_label:S(x);name_description:S(x XenServer);memory_overhead:I(1027997696);allowed_operations:.....
    at Function.wrap (/home/node/xen-orchestra/packages/xen-api/src/_XapiError.js:16:12)
    at /home/node/xen-orchestra/packages/xen-api/src/transports/json-rpc.js:35:27
    at AsyncResource.runInAsyncScope (async_hooks.js:197:9)
    at cb (/home/node/xen-orchestra/node_modules/bluebird/js/release/util.js:355:42)
    at tryCatcher (/home/node/xen-orchestra/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/node/xen-orchestra/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/home/node/xen-orchestra/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/home/node/xen-orchestra/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/home/node/xen-orchestra/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/home/node/xen-orchestra/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/home/node/xen-orchestra/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/home/node/xen-orchestra/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/node/xen-orchestra/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:464:21)
    at process.topLevelDomainCallback (domain.js:147:15)
    at process.callbackTrampoline (internal/async_hooks.js:129:24)"`

**Comment by mspencerl87** [comment]
I'm also having issues with stats. I'm also accumulating thousands of tasks 
Xapi#getResource /rrd_updates (on xcp-ng-01) 0%

Tried rebuilding XOA, removing datastores, rebooting host. Deleting backup/snapshots.
Everything but re-installing xcp-ng.

**Comment by olivierlambert** [comment]
That's likely because your host is behind a NAT.
