### ISSUE TITLE
Cannot mount NTFS for File Recovery

### ISSUE THREAD

**Issue by EpicLPer** [Ezka77/xen-orchestra-ce#49]
I'm not sure if this is an issue with the Docker Image itself or how Xen Orchestra/XCP-ng in general handles this, but according to the forums the "host OS" needs to support NTFS. Since this is a Docker container, I doubt that's true still for the Host OS, and think the Docker Image itself needs support to handle NTFS drives?

Whenever I try a file level recovery it simply throws the error "Error while scanning disk". Here's the forum thread: https://xcp-ng.org/forum/topic/6301/file-level-restore-results-in-error-while-scanning-disk?_=1662799558330

**Comment by Ezka77** [comment]
Hi @EpicLPer, 

Yes you're right about the "host OS need to support NTFS" and as here it's the docker, you need a kernel module to be able to mount this vmdk. As I'm away (vacation leave) you will have to wait a couple of weeks until I'll add this package to the docker image.

Meanwhile you can:
- find how to get a console in the docker; quick tip: run the docker with something like 
```docker run ezka77/xen-orchestra-ce:latest /bin/sh```
and install the apk : 
```apk update && apk add ntfs-3g``` 
next start the xo server:
```cd /home/node/xen-orchestra/packages/xo-server/ ; /bin/remco```
and do your tests, if it works consider the next step as this will work until the container stops.
- fork this repo, change the Dockerfile, add this package in the install cmd line, build your docker image and use it ; optional: if it works ask for a merge request (less work for me 😁)

**Comment by Ezka77** [comment]
For the amd64 the ntfs-3g package is now included, but for arm there is an issue. Let me know if it works for you.
