### ISSUE TITLE
Update to XO 5.18 ?

### ISSUE THREAD

**Issue by mhoffmann75** [Ezka77/xen-orchestra-ce#5]
Xen-Orchestra 5.18 is out now.
https://xen-orchestra.com/blog/xen-orchestra-5-18/

Can you update code?

**Comment by Ezka77** [comment]
Hi, 
yep see they push 5.18.0 on master. I was expecting they push 5.18 on stable branch too, it's easiest to avoid some random issues that can occur between major commits. If 5.18 doesn't pop on stable I'll use the master branch to make an update at the end of this week.

To me their release process from the day they merged all their repos, is not so clear now.
