### ISSUE TITLE
please add auth-oidc plugin

### ISSUE THREAD

**Issue by rave-net** [Ezka77/xen-orchestra-ce#54]
In XOA 5.80 the auth-oidc plugin was added for open id connect based authentication.  This is missing from the -ce version and would be great to have.

**Comment by Ezka77** [comment]
Hi,

sure, but if you are in hurry you can add it here:
https://github.com/Ezka77/xen-orchestra-ce/blob/22636d7684f96f02b3da764d8c1c07e077310855/alpine/link_plugins.sh#L6

build your image and you can work with it in 5mn ; if it works send me a MR :grin: otherwise I'll do it asap
