### ISSUE TITLE
File based restore not working: XO_server  | fuse: device not found, try 'modprobe fuse' first

### ISSUE THREAD

**Issue by Trufax** [Ezka77/xen-orchestra-ce#57]
Hi,

i try to use the filerestore from a backup but the UI just shows a red warning and the logs show the following:
```

XO_server  | fuse: device not found, try 'modprobe fuse' first
XO_server  | 2023-06-22T13:52:50.681Z xo:api WARN user@user.net | backupNg.listFiles(...) [42ms] =!> Error: Command failed: mount --options=loop,ro,norecovery --source=/tmp/akedcxeywds/vhd0 --target=/tmp/4kp4cwhl51p
XO_server  | mount: /tmp/4kp4cwhl51p: mount failed: Operation not permitted.


```
The disk is a local disk on the host which is mounted inside the container.

modprope fuse in the container shows the following:

```
7d397c531662:/home/node/xen-orchestra/packages/xo-server# modprobe fuse
modprobe: can't change directory to '/lib/modules': No such file or directory
```

**Comment by Ezka77** [comment]
Hi,

First thought: does your container is allowed to use the mount command ?

More info here: https://docs.docker.com/engine/reference/commandline/run/#privileged

If you are using the docker-compose file from this repo see this section: https://github.com/Ezka77/xen-orchestra-ce/blob/master/docker-compose.yml#L15-L18

Uncomment the line 15, remove the next 3 lines and give a try. Let me know the result

**Comment by Trufax** [comment]
Hi,

i use the compose file from the repo, enabled privileged but now i get the following error:

```
XO_server  | 2023-06-26T12:46:46.418Z xo:api WARN user@user.net | backupNg.listFiles(...) [904ms] =!> Error: Command failed: mount --options=loop,ro,norecovery --source=/tmp/oo84unnich/vhd0 --target=/tmp/n2fef2e1cw
XO_server  | mount: /tmp/n2fef2e1cw: failed to setup loop device for /tmp/oo84unnich/vhd0.
XO_server  | 
```

**Comment by Ezka77** [comment]
on your host, make sure you have the `loop` kernel module, something like `lsmod | grep loop` should give you a match. If not, you need to load that module `modprobe loop` and now it should match something.

If you have that kernel module and the same message ... :sweat_smile: I'll be out of idea to help you :man_shrugging: 

NB: maybe the fuse module too ?

**Comment by Trufax** [comment]
So `lsmod | grep loop` returns nothing but also after `modprobe loop` it returns nothing. Its normal Ubuntu 22.04 nothing special. It seems to work for discs which are not LVMs. I have 1 VM which has non LVM discs and it can list the files.

**Comment by Ezka77** [comment]
Do you try to; `losetup --partscan -f <your_img>` and use LVM tools like `vgscan` to see if both are working on your host and in the container.

I think there isn't LVM in the docker image, and if it works with "flat" image it seems that's the issue.

**Comment by Trufax** [comment]
Sorry took some time to work on this again. Yes i agree there seems to be no LVM Support in the container therfore it wan only work with "flat" images. Do you see this as possibility to be added or does it need a custom base image which would be too much work ?

**Comment by Ezka77** [comment]
I've added the lvm2 package to the docker image, it should help to spawn lvm commands.

**Comment by Trufax** [comment]
Wow thanks for picking this up again! Just did a quick test and indeed it seems to work. I could list folders and files from LVM volumes. I had to mount a few devices in the container first but than it worked:
```
        devices:
            - "/dev/fuse:/dev/fuse"
            - "/dev/loop-control:/dev/loop-control"
            - "/dev/loop0:/dev/loop0"
```

**Comment by Ezka77** [comment]
To use these devices and the lvm commands, is your docker compose service using the `privileged : true` flag ? or the SYS_ADMIN capability is enough ?

I'll add these configuration lines to docker-compose.yml as a reminder in case anyone needs lvm in the future.

**Comment by Trufax** [comment]
It needs `privileged : true` to work. `SYS_ADMIN` seems not to be enough

**Comment by Trufax** [comment]
Hey just did some testing and since some update it does not work anymore. Again the same error we had initially:

```
XO_server  | 2024-02-14T09:34:53.570Z xo:api WARN xxxxxx@xxxxx.net | backupNg.listFiles(...) [1s] =!> Error: Command failed: mount --options=loop,ro,norecovery --source=/dev/data-vg/data-lv --target=/tmp/p39t7ib0dm
XO_server  | mount: /tmp/p39t7ib0dm: failed to setup loop device for /dev/mapper/data--vg-data--lv.
XO_server  |
```

**Comment by Trufax** [comment]
Hey, just tested this and yes i still have this issue. Thanks for picking it up again.
