### ISSUE TITLE
Installs 'test-plugin' which is practically blank

### ISSUE THREAD

**Issue by gb-123-git** [Ezka77/xen-orchestra-ce#58]
"test" & "test-plugin" need to be filtered out from 'plugins' section, else they also get installed.

The link_plugins.sh does not have them but somehow they are getting compiled in the latest image pushed in dockerhub and getting auto-loaded at XO start.

Also need to add the following plugin :
audit(v0.10.5) - Audit plugin for XO-Server

**Comment by Ezka77** [comment]
Humm!

First: I'm surprised that there is the tests plugins !
Second: if there is the tests plugins ... I'm surprised that the audit plugin isn't there! :joy: 

I've `docker compose up` a latest image and the audit plugin is loaded by default for me, so the plugin is "installed", loaded and the only part that require a user interaction is the "active" button:

![image](https://github.com/Ezka77/xen-orchestra-ce/assets/1818604/86096724-1342-4203-9261-69197f75de48)

I'll have a look for these tests plugins.

**Comment by Ezka77** [comment]
Well I find out that the xo-server looks in his parent to add all the plugins. As we do not configure this part I think it's the default :shrug: ; so I've remove the step where we "link" the plugins in the node_modules directory as it is useless now.

**Comment by gb-123-git** [comment]
>Second: if there is the tests plugins ... I'm surprised that the audit plugin isn't there! 😂

The 'audit' plugin is there in the launched XO, I was just trying to update your links.sh file, since it was not there in the file. But now since the file is not required, I guess good riddance and 1 less thing to maintain. 😜 

And thank you sooo much for your prompt response ! You are really amazing !
