### ISSUE TITLE
Self signed certs bug fix

### ISSUE THREAD

**Issue by jv545642** [Ezka77/xen-orchestra-ce#62]
Hello,

Can you please implement the fix for this bug? I would greatly appreciate it. 

I think the only action is to use the update from latest commit today.

https://xcp-ng.org/forum/topic/8618/restoring-from-backup-error-self-signed-certificate/39
https://xcp-ng.org/forum/topic/8690/error-self-signed-certificate-after-a-few-days/5

Thank you!

**Comment by jv545642** [comment]
Hi,

I just wanted to add that manually building the image results in an error:

```
config.status: error: in `/home/node/libvhdi':
config.status: error: Something went wrong bootstrapping makefile fragments
    for automatic dependency tracking.  If GNU make was not used, consider
    re-running the configure script with MAKE="gmake" (or whatever is
    necessary).  You can also try re-running configure with the
    '--disable-dependency-tracking' option to at least be able to build
    the package (albeit without support for automatic dependency tracking).
See `config.log' for more details
The command '/bin/sh -c ./configure' returned a non-zero code: 1
```

**Comment by Ezka77** [comment]
1. I can build the image on my machine, I think something is wrong with your setup beside it works in CI so I would advise you to look how to build with `docker compose` (tips: it takes one line to add to the `docker-compose.yml` file ; I'll add it in a future commit)
2. It seems fine now, as the report is 2 weeks old the CI should have pick the latest patch from the git repos.

Thanks for the bug report :+1

**Comment by jv545642** [comment]
Thank you for replying. It's much appreciated.
