### ISSUE TITLE
missing HUB and XOSTOR

### ISSUE THREAD

**Issue by tostr7191** [Ezka77/xen-orchestra-ce#64]
Hi

Since I am evaluating xcp-ng for a production env at the moment, I wanted to have all features available, so I went with your docker image. However, in the interface I am missing XOSTOR and HUB, which just show "XOSTOR/HUB is available in XOA" with a link to xoa vm installation page.

I should also note that the hosts are running 8.3 beta, however these menu items did work when I had the pre-packaged xoa vm running.

Am I missing something and this is expected behaviour, or a configuration issue on my side?

Thanks & cheers
tostr

**Comment by olivierlambert** [comment]
Hi,

If you want to evaluate the entire solution with the Hub and XOSTOR, you must use XOA, since those are extra service or feature that aren't available directly on XO only. XOA provides a trial that can be extended many times by just asking 👍 
Also, XOA will be closer to your future production setup since it's the version sold by Vates (with QA, remote assistance and so on)

**Comment by tostr7191** [comment]
Hi Olivier

Thanks for your quick answer, so then my understanding is correct that XOSTOR *UI* is not part of the open source offering, but command line access is?

I agree with the official XOA generally, however the setup we are looking at and the pricing model offered by vates seem to not have a good match, we will see what we can figure out.

cheers
tostr

**Comment by olivierlambert** [comment]
Everything is open source, but the UI part (which makes it more turnkey) isn't visible in XO from the sources but only XOA. However, it's not complicated to set it up via the CLI and it's even extensively documented: https://xcp-ng.org/forum/topic/5361/xostor-hyperconvergence-preview

So you can have the choice to go with the turnkey+support solution or the source one :) Also you can use our trial to test everything yourself for free for 1 month.

**Comment by tostr7191** [comment]
Oh I see. Thank you so much for your help, I only realised now that you are not some random person offering a docker-compose, but actually the CEO of vates. That you provide a solution to get access to the features yourself I find very reassuring regarding the open source spirit of vates, which for us is an important consideration as a small hosting company.

Salutations depuis Bâle
tostr

**Comment by olivierlambert** [comment]
I'm not the owner here, just following this repo but I wanted to answer your questions, even on 3rd party provider. Our doc provides everything you need to install everything "from the sources" (see https://xen-orchestra.com/docs/installation.html#from-the-sources). It will be similar for XOSTOR, "source" install if you like, so you always have the choice to go for "turnkey + support" or "source" route, while having a free trial first.

edit: and no problem, you are welcome :) Salutations depuis Grenoble 😉
