### ISSUE TITLE
update of plugins

### ISSUE THREAD

**Issue by christianuhlmann** [Ezka77/xen-orchestra-ce#7]
as mentioned in https://github.com/vatesfr/xen-orchestra/issues/2876 the will not update the npm packages. 
> Indeed, the plugin did not update because we don't maintain the npm packages. If you install xo from the source, the packages will not update automatically, you need to do it manually by updating xo and linking the plugin to the node modules.

did you know what we have todo to upgrade the plugins to the latest version?
i would use the xo-server-usage-report

**Comment by Ezka77** [comment]
well the plugins are in the sources, the `yarn` command should build the plugins but ... I do not know how to install these builded plugins. As soon as I know how :

**Comment by Ezka77** [comment]
Yeah I've guessed that, when I build the project I think plugins are builded too. As soon as I know how I *"you need to do it manually by updating xo and linking the plugin to the node modules."* I'll add the trick.

**Comment by christianuhlmann** [comment]
ok
i have an idea, later i will try this in a docker file.
in xo_server running container i habe to do this:

`cd /home/node/xen-orchestra/packages/xo-server-usage-report`
`yarn link`
`cd /home/node/xen-orchestra/packages/xo-server/node_modules/`
`yarn link "xo-server-usage-report"`
and restart the container

i dont know what was the right step, but i get the report in the actual version 0.5.0

**Comment by christianuhlmann** [comment]
i have created a pull request https://github.com/Ezka77/xen-orchestra-ce/pull/8 for update plugins and node:6-alpine with Yarn 1.7.0 for update to xo 5.20

**Comment by Ezka77** [comment]
I've managed to link the plugins in the build process by using your command line pattern, it should work nicely with less layers on the final image.
