### ISSUE TITLE
error in redis

### ISSUE THREAD

**Issue by christianuhlmann** [Ezka77/xen-orchestra-ce#9]
Hi
I have a strange phenomenon, if I want to log in with my user from another computer (same OS, same browser), this will not work.
in the xo docker log I see the following:
xo:
>  [Warn] Possibly unhandled rejection: ReplyError: MISCONF Errors writing to the AOF file: Invalid argument
     at parseError (/home/node/xen-orchestra/node_modules/redis-parser/lib/parser.js:193:12)
     at parseType (/home/node/xen-orchestra/node_modules/redis-parser/lib/parser.js:303:14)

redis:

>  1:M 16 Jun 13:59:55.491 # Error writing to the AOF file: Permission denied
 1:M 16 Jun 13:59:55.509 # AOF write error looks solved, Redis can write again.

after a few seconds (about 60, then it comes to a timeout)

do you have an idea what could be the problem here?
On my main host, the login screen is no longer, because I clicked "Remember Me".

greetings

Christian

**Comment by christianuhlmann** [comment]
very strange, I have certainly tried 10 times. each with restarts and long wait times after the restarts before I opened the issue.
it never worked, now 3 hours later still a try and it works immediately without errors. I'm out ... sorry

**Comment by Ezka77** [comment]
Hi Christian,
it seems to be a permission issue, the redis error is quite explicit here. If you're using the docker-compose file from this repos it create a **volumes** directory on the host. You can try to remove it if you don't need the saved datas, or a `sudo chown 1000:1000 volumes -R` it should fix all the permissions, make a backup and recreate both containers (a `restart` will not be enough).

**Comment by christianuhlmann** [comment]
hi,

now i am get this error by add an SMB remote for backups under settings -> remotes:

```
remote.create
{
  "name": "paladin-storage-backup-xenserver",
  "url": "smb://user:pass@HOME\\\\<IP-Address>\\backup\u0000xenserver"
}
{
  "message": "MISCONF Errors writing to the AOF file: Invalid argument",
  "stack": "ReplyError: MISCONF Errors writing to the AOF file: Invalid argument
    at parseError (/home/node/xen-orchestra/node_modules/redis-parser/lib/parser.js:193:12)
    at parseType (/home/node/xen-orchestra/node_modules/redis-parser/lib/parser.js:303:14)",
  "command": "DEL",
  "args": [
    "xo:remote:e6f913d9-e7b0-4e95-877f-d684a780d191"
  ],
  "code": "MISCONF"
}
```

i use your docker-compose file with the volumes but i need the saved data.

after stop and rm the container 
`docker-compose down --remove-orphans`
and prune the docker enviroment
`docker system prune --volumes`
and change the ownershop
`sudo chown 1000:1000 <vol-path>`
and recreate the container again
`docker-compose up -d`

nothing changed :(

owner of the files are root:root!

**Comment by christianuhlmann** [comment]
OK
Now I have an idea what it could be.
for the volumes I have used nfs shares, if I use local space it works.
as well as a glusterfs volume works, so I say goodbye to nfs and everything works.

can you confirm that it could be due to nfs?
I can not really imagine that, but if that's the case then it's ok for me

**Comment by Ezka77** [comment]
Yeah, using NFS for the volume directory can lead to this kind of things. NFS add a lock mechanism on files, and databases system doesn't like that (or you need to tweak your mount point to make it fast but less reliable). If you need to save/share a directory with a database you need to use a more low-level FS abstraction.

NB: May be a NFS expert will tell you the opposite, but it's my experience ;)

**Comment by christianuhlmann** [comment]
ok, then i will close the issue
thanks
